baseURL = "https://www.hagelandseoffroadparels.be/"
languageCode = "nl-be"
theme = "hageland"

[params]
title = "A.C. Hagelandse Off-Road Parels"
github = "https://github.com/stockmansy/hagelandseoffroadparels"
facebook = "https://www.facebook.com/p/Fit-Move-sportclub-Kortenaken-100088017470117/"
sbtoken = "TOKEN_HERE"
logo = "assets/img/bike.svg"
phone = "123456"
twitter = "#"
favicon = "assets/favicon.ico"

[menu]

[[menu.main]]
name = "Welkom"
URL = "#welkom"
weight = 1

[[menu.main]]
name = "2025 editie"
URL = "#huidige_editie"
weight = 2

[[menu.main]]
name = "Afstanden"
URL = "#afstanden"
weight = 3

[[menu.main]]
name = "Vorige edities"
URL = "#vorige_editie"
weight = 4

[[menu.main]]
name = "Over ons"
URL = "#over_ons"
weight = 5
