diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor="C:\\Program Files\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
credential.helper=manager
pull.rebase=false
user.name=stockmansy
user.email=stockmans_y@hotmail.com
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
gui.recentrepo=C:/Projects/Samples/ES6
gui.recentrepo=C:/Projects/Samples/Angular-Forms
safe.directory=N:/Projects/NoeSBot/NoeS bot
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.staging.url=https://github.com/stockmansy/hagelandseoffroadparels.git
remote.staging.fetch=+refs/heads/*:refs/remotes/staging/*
remote.origin.url=https://github.com/stockmansy/hagelandseoffroadparels.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
