name = "Hageland"
license = "Unlicenced"
licenselink = "https://github.com/stockmansy/hagelandseoffroadparels/LICENSE"
private = true
description = "A website made for family by Yannick Stockmans"
homepage = "https://www.hagelandseoffroadparels.be"
tags = ["sport", "bike", "belgium"]
features = ["responsive"]
min_version = "0.121.2"

[author]
  name = "Yannick Stockmans"
  homepage = "https://www.hagelandseoffroadparels.be"
  repo = "https://github.com/stockmansy/hagelandseoffroadparels"